WebShopProject/Controllers/Admin/AdminProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Humanizer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using WebShopProject.Data;
using WebShopProject.Models;

namespace WebShopProject.Controllers.Admin
{
    [Authorize(Roles = "Admin")]
    public class AdminProductController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly FnHelper _fnHelper;
        public AdminProductController(ApplicationDbContext context)
        {
            _context = context;
            _fnHelper = new FnHelper(context);
        }

        // GET: AdminProduct
        public async Task<IActionResult> Index(string? message)
        {
            if(message != null) ViewBag.Message = message;  
            List<Product> products = _context.Product.ToList();

            if (products == null) return View("Index",new List<Product>());

            foreach (var item in products)
            {
                item.ProductImage = _context.ProductImage.Where(x => x.ProductId == item.Id).ToList();
                item.ProductCategory = _context.ProductCategory.Where(x => x.ProductId == item.Id).ToList();
                if (item.Description.Length > 50)
                {
                    item.Description = item.Description.Truncate(50);
                }
            }


            return View(products);
        }

        // GET: AdminProduct/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: AdminProduct/Create
        public IActionResult Create()
        {
            
            Product product = new Product();
            if (_context.ProductCategory != null)
            {
                product.Category = _context.Category.ToList();
            }
            return View(product);
        }

        // POST: AdminProduct/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string? chkDefaultImage,string? chkCategory,int? selectCategoryId, [Bind("Id,Name,Description,Active,Quantity,Price")] Product product)
        {
            ModelState.Remove("OrderItem");
            ModelState.Remove("Category");
           
            if (chkDefaultImage == "on" || HttpContext.Request.Form.Files.Count > 0) ModelState.Remove("ProductImage");
            if (chkCategory == "on")
            {
                ModelState.Remove("ProductCategory");
                ModelState.Remove("selectCategoryId");
            }
            else if(selectCategoryId == null)
            {
                ModelState.Remove("ProductCategory");
                ModelState.AddModelError("ProductCategory", "Category not selected!");
            }else
            { ModelState.Remove("ProductCategory"); }

            if (product.Quantity == 0)
            {//allow adding product with quantity 0
            
                ModelState.Remove("Quantity");
            }

            if (ModelState.IsValid)
            {
                _context.Add(product);

                await _context.SaveChangesAsync();

                if (product.Id > 0 && HttpContext.Request.Form.Files.Count > 0)
                {
                    var imageFile = HttpContext.Request.Form.Files.FirstOrDefault();

                    ProductImage productImage =  await FnHelper.CreateProductImage(imageFile, product.Id);
                    
                    _context.Add(productImage);
                    _context.SaveChanges();
                }

                if (product.Id > 0 && selectCategoryId != null)
                {
                    ProductCategory productCategory = new ProductCategory()
                    {
                        CategoryId = (int)selectCategoryId,
                        CategoryName = _context.Category.FirstOrDefault(x => x.Id == selectCategoryId).Name,
                        ProductId = product.Id,
                        ProductName = product.Name

                    };

                    _context.Add(productCategory);
                    _context.SaveChanges();
                }



                return RedirectToAction(nameof(Index));
            }

            product.Category = _context.Category.ToList();
            return View(product);
        }
    

        // GET: AdminProduct/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }

            var product = await _context.Product.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            foreach (var productImage in _context.ProductImage.ToList())
            {
                if(product.Id == productImage.ProductId)
                {
                    product.ProductImage.Add(productImage);
                }
            }

            product.Category = _fnHelper.GetProductCategories(product.Id);

            return View(product);
        }

        // POST: AdminProduct/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Active,Quantity,Price")] Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            ModelState.Remove("OrderItem");
            ModelState.Remove("ProductImage");
            ModelState.Remove("ProductCategory");
            ModelState.Remove("Category");
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: AdminProduct/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: AdminProduct/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Product == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Product'  is null.");
            }
            var product = await _context.Product.FindAsync(id);
            if (product != null)
            {
                _context.Product.Remove(product);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<ActionResult> EditProductCategory(int? id, string? error)
        {
            if (id == null) 
                ViewBag.Error = ("Id is null.");

            if (error != null)
            {
                ViewBag.Error = error;
            }

            var product = _context.Product.Find(id);




            if (product != null)
            {
                product.ProductCategory = _context.ProductCategory.Where(x => x.ProductId == id).ToList();

                //add only categories which are not added to product
                var catId = product.ProductCategory.Where(x => x.ProductId == id).Distinct().ToList();
                product.Category = new List<Category>();
                foreach (var item in _context.Category)
                {
                    if(!catId.Any(x => x.CategoryId == item.Id))
                    {
                        product.Category.Add(item);
                    }
                }
            }

         

            foreach(var item in product.ProductCategory)
            {
                item.CategoryName = _context.Category.Where(x => x.Id == item.CategoryId).FirstOrDefault().Name;
            }

            return View(product);
        }

   
        public async Task<ActionResult> DeleteProductCategory(int? productId, int? categoryId)
        {
            if (productId == null) return Problem("Product Id is null");
            if (categoryId == null) return Problem("Category Id is null");

            var productCategory = _context.ProductCategory.Where(x => x.ProductId == productId &&  x.CategoryId == categoryId).FirstOrDefault();

            if(productCategory != null)
            {
                _context.ProductCategory.Remove(productCategory);

WebShopProject/Controllers/Admin/AdminProductImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebShopProject.Data;
using WebShopProject.Models;

namespace WebShopProject.Controllers.Admin
{
    [Authorize(Roles = "Admin")]
    public class AdminProductImageController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AdminProductImageController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: AdminProductImage
        public async Task<IActionResult> Index(int Id)
        {
        
            if (_context.ProductImage != null)
            {
                List<ProductImage> producImages = _context.ProductImage.ToList();
                if (producImages.Any(x => x.ProductId == Id))
                {
                    ViewBag.ProductId = Id;
                    return View(producImages.Where(x => x.ProductId == Id));
                }else
                {
                    ViewBag.ProductId = Id;
                    return View(new List<ProductImage>() );
                }
            }
            else
            {
                ViewBag.ProductId = Id;
                return View(new List<ProductImage>());
            }
              
             
        }

        // GET: AdminProductImage/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ProductImage == null)
            {
                return NotFound();
            }

            var productImage = await _context.ProductImage
                .FirstOrDefaultAsync(m => m.Id == id);
            if (productImage == null)
            {
                return NotFound();
            }

            return View(productImage);
        }


        // GET: AdminProductImage/Create
        public IActionResult Create(int? id)
        {
            if (id == null || _context.Product.Count(x => x.Id == id) == 0) { return RedirectToAction("AdminProduct", "Index"); }

            return View(new ProductImage() { ProductId = (int)id});
        }

        // POST: AdminProductImage/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( ProductImage productImage)
        {
            if (productImage.ProductId == null || productImage.ProductId == 0) return NotFound();

            if (_context.Product.Any(x => x.Id == productImage.ProductId))
            {
                productImage.ProductName = _context.Product.Where(x => x.Id == productImage.ProductId).FirstOrDefault().Name;
                ModelState.Remove("ProductName");
            }
            ModelState.Remove("FileName");
            ModelState.Remove("Id");
            if (ModelState.IsValid)
            {
                if (HttpContext.Request.Form.Files.Count > 0)
                {
                    var imageFile = HttpContext.Request.Form.Files[0];
                    productImage = await FnHelper.CreateProductImage(imageFile, productImage.ProductId, productImage.IsMainImage);
                }else
                {
                    ModelState.AddModelError("FileName", "Image upload required.");
                    return View(productImage);
                    return NotFound(); //TODO SMT BETTER MAYBE
                }
                

                
                productImage.Id = 0;
                _context.Add(productImage);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new {id = productImage.ProductId});
            }
            return View(productImage);
        }

        // GET: AdminProductImage/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ProductImage == null)
            {
                return NotFound();
            }

            var productImage = await _context.ProductImage.FindAsync(id);
            if (productImage == null)
            {
                return NotFound();
            }
            return View(productImage);
        }

        // POST: AdminProductImage/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProductId,Name,IsMainImage,FileName")] ProductImage productImage)
        {
            if (id != productImage.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(productImage);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductImageExists(productImage.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(productImage);
        }

        // GET: AdminProductImage/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ProductImage == null)
            {
                return NotFound();
            }

            var productImage = await _context.ProductImage
                .FirstOrDefaultAsync(m => m.Id == id);
            if (productImage == null)
            {
                return NotFound();
            }

            return View(productImage);
        }

        // POST: AdminProductImage/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ProductImage == null)
            {
                return Problem("Entity set 'ApplicationDbContext.ProductImage'  is null.");
            }
            var productImage = await _context.ProductImage.FindAsync(id);
            if (productImage != null)
            {


                var fileName = "wwwroot" + productImage.FileName.Replace("/", "\\");
                System.IO.File.Delete(fileName);
                _context.ProductImage.Remove(productImage);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductImageExists(int id)
        {
          return (_context.ProductImage?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebShopProject/Views/AdminProduct/Create.cshtml
@model WebShopProject.Models.Product

@{
    ViewData["Title"] = "Create";
}

<h1>Create product</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" id="CreateProduct" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" > </textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" checked="checked" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" type="number" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" type="number" min="1" step="any" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
                
            </div>
            <div class="form-group mt-2">
                <label class="control-label">Use default image</label>
                <input type="checkbox" id="chkDefaultImage" name="chkDefaultImage" onclick="CheckDefault()" />
            </div>

            <div class="form-group" id="imageUpload" >
                <input type="file" id="productImage" asp-for="ProductImage" class="form-control" onchange="PicturePreview()" />
                <span asp-validation-for="ProductImage" class="text-danger"></span>
            </div>

            <div class="form-group mt-3">
                <label class="control-label">Upload without category</label>
                <input type="checkbox" id="chkCategory" name="chkCategory" onclick="CheckDefault()" />
            </div>

            <div class="form-group" id="showCategory">
                @if(Model.Category != null)
                {

                    @*TODO category dropdown*@


                    <select class="form-select" name="selectCategoryId" aria-label="Select category">
                        <option selected>Category</option>
                        @foreach(var item in Model.Category)
                        {
                            <option value="@item.Id">@item.Name</option>    
                        }

                        
                    </select>
                    <span asp-validation-for="ProductCategory" class="text-danger"></span>
                }else
                {
                  <div>No categories in database.</div> 
                }
            </div>

            <div class="form-group mt-3">
                <input type="submit" value="Create" class="btn btn-success" />
                <a class="btn btn-dark " asp-action="Index">Back to Products</a>
            </div>

        </form>
    </div>
    <div class="col-md-2"></div>
    <div class="col-md-4">
        <img id="defaultProductImage" src="~/images/default.png" height="500"/>
    </div>
</div>

<div>

</div>
@section scripts{
    <script>
        function PicturePreview() {
            var preview = document.querySelector('#defaultProductImage');
            
            var isSelected = document.querySelector('#productImage') !== null;

            if(isSelected)
            {
                var productImage = document.querySelector('#productImage').files[0];
            }
            var reader = new FileReader();

            reader.onloadend = function() {
                preview.src = reader.result;
            }
            if(isSelected)
            {
                reader.readAsDataURL(productImage);
            }else{
                preview.src = "";
            }

            
        }


        function CheckDefault(){
            var checkBoxImage = document.getElementById('chkDefaultImage');
            var checkBoxCategory = document.getElementById('chkCategory');
            
            var imageUpload = document.getElementById('imageUpload');
            var showCategory = document.getElementById('showCategory');

            if (checkBoxCategory.checked == true) {
                showCategory.style.display = "none";
            } else {
                showCategory.style.display = "block";
            }

            if(checkBoxImage.checked == true)
            {
                imageUpload.style.display = "none";
            }else{
                imageUpload.style.display = "block";
            }
        }               

        
    </script>
}

WebShopProject/Views/AdminProduct/Delete.cshtml
@model WebShopProject.Models.Product

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="btn btn-dark" asp-action="Index">Back to List</a>
    </form>
</div>

WebShopProject/Views/AdminProduct/Details.cshtml
@model WebShopProject.Models.Product

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
</div>
<div class="row">
    <div class="d-inline-flex">
        <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> 
        <a class="btn btn-dark ms-2" asp-action="Index">Back to List</a>
    </div>
</div>

WebShopProject/Views/AdminProduct/Edit.cshtml
@model WebShopProject.Models.Product

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form  asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="text-center mt-3">
                Categories
            </div>
            <hr />
            <div class="">
                @foreach(var item in Model.Category)
                {
                    
                        <label class="btn btn-secondary mt-1"> @item.Name</label>
                 
                }
            </div>
            <hr />

            <div class="form-group">
                <input class="btn  btn-success mt-3" href="#" type="submit" value="Save" />
            </div>
        </form>
    </div>
    <div class="col-md-2"></div>
    <div class="col-lg-6"> 
        @if (Model.ProductImage != null)
        {
            <div class="col-sm-4">
                <div id="pictureCarousel" class="carousel slide">
                    <ol class="carousel-indicators">
                        <li data-bs-target="#pictureCarousel" data-bs-slide-to="0" class="active"></li>
                        @if (Model.ProductImage.Count > 1)
                        {
                            for (int i = 1; i < Model.ProductImage.Count; i++)
                            {
                                <li data-bs-target="#pictureCarousel" data-bs-slide-to="@i"></li>
                            }
                        }
                    </ol>
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <div class="img-thumbnail">
                                @if (Model.ProductImage != null)
                                {
                                   
                                    if (Model.ProductImage.Where(x => x.IsMainImage == true).FirstOrDefault() != null)
                                    {
                                        var imgSrc = Model.ProductImage.Where(x => x.IsMainImage == true).FirstOrDefault();
                                        Model.ProductImage.Remove(imgSrc);

                                        <img src="@imgSrc.FileName" class="img-fluid img-thumbnail" />
                                    }else
                                    {
                                        var imgSrc = Model.ProductImage.FirstOrDefault();
                                        Model.ProductImage.Remove(imgSrc);

                                        <img src="@imgSrc.FileName" class="img-fluid img-thumbnail" />
                                    }

                                   

                                }else
                                {
                                    <img src="~/images/default.png" class="img-fluid img-thumbnail" />
                                }
                            </div>
                        </div>
                     
                        @foreach (var item in Model.ProductImage)
                        {
                            <div class="carousel-item">
                                <div class="img-thumbnail">
                                    <img src="@item.FileName" class="img-fluid" />
                                </div>
                            </div>
                        }
                    </div>
                    <a data-bs-target="#pictureCarousel" class="carousel-control-prev" role="button" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    </a>
                    <a data-bs-target="#pictureCarousel" class="carousel-control-next" role="button" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    </a>
                </div>
            </div>
        }
        else
        {
            <div class="image-container">
                <img src="~/images/default.png" class="img-fluid" />
            </div>
        }
         
    </div>
  

</div>
<div class="row mt-2">
    <div class="d-inline-flex">
        <a class="btn btn-warning" asp-controller="AdminProductImage" asp-action="Index" asp-route-id="@Model.Id">Edit images</a>
        <a class="btn btn-warning ms-2" asp-action="EditProductCategory" asp-route-id="@Model.Id">Edit category</a>
        <a class="btn btn-dark ms-2" asp-action="Index">Back to Products</a>
    </div>
</div>

    