WebShopProject/Controllers/Admin/AdminCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebShopProject.Constants;
using WebShopProject.Data;
using WebShopProject.Models;

namespace WebShopProject.Controllers.Admin
{
    [Authorize(Roles = "Admin")]
    public class AdminCategoryController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AdminCategoryController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: AdminCategory
        public async Task<IActionResult> Index()
        {
              return _context.Category != null ? 
                          View(await _context.Category.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Category'  is null.");
        }

        // GET: AdminCategory/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Category == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: AdminCategory/Create
        public IActionResult Create()
        {

            return View();
        }

        // POST: AdminCategory/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Category category)
        {
            ModelState.Remove("ProductCategory");
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: AdminCategory/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Category == null)
            {
                return NotFound();
            }

            var category = await _context.Category.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: AdminCategory/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: AdminCategory/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Category == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: AdminCategory/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Category == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Category'  is null.");
            }
            var category = await _context.Category.FindAsync(id);
            if (category != null)
            {
                _context.Category.Remove(category);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
          return (_context.Category?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebShopProject/Controllers/Admin/AdminUserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Runtime.CompilerServices;
using WebShopProject.Constants;
using WebShopProject.Data;
using WebShopProject.Models;

namespace WebShopProject.Controllers.Admin
{
    [Authorize(Roles = "Admin")]
    public class AdminUserController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IUserStore<ApplicationUser> _userStore;
        private readonly FnHelper _fnHelper;
        public AdminUserController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, 
            RoleManager<IdentityRole> roleManager, SignInManager<ApplicationUser> signInManager, IUserStore<ApplicationUser> userStore)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
            _fnHelper = new FnHelper(context, userManager, roleManager);
            _signInManager = signInManager;
            _userStore = userStore;
        }

        public IActionResult Index(string? message, string? error)
        {
            if (_userManager == null || _userManager.Users == null)
            {
                ViewBag.Error = "No users in DB.";
                return View(new AppUserViewModel());
            }
            
            if(message != null) ViewBag.Message = message;
            if(error != null) ViewBag.Error = error;    

            var users = _userManager.Users.Select(x => new AppUserViewModel()
            {
                UserId = x.Id,
                UserName = x.UserName,
                Email = x.Email,
                TwoFactorAuthActive = x.TwoFactorEnabled,
                EmailConfirmed = x.EmailConfirmed,
                Role = string.Join(',',_userManager.GetRolesAsync(x).Result.ToArray())
            });


            return View(users);
        }


        public  IActionResult Details(string? id) 
        {
            //check if user is auth and exists
            ApplicationUser user = _context.Users.Where(x => x.Id == id).FirstOrDefault();
            if (user == null)
            {
                return RedirectToAction("Index",new { error = "User not found." });
            }

            user.UserRole = _fnHelper.GetUserRole(id);

            return View(user);
        }

        public IActionResult Edit(string? id,string? message)
        {
            if (message != null) ViewBag.Message = message;
            var user = _context.Users.Find(id);
            //user.UserRole = _userManager.GetRolesAsync(user).Result.FirstOrDefault();
 
            ViewBag.UserRoles = _roleManager.Roles;

            ViewBag.SelectCountry = _context.Country; 
            user.UserRole = _fnHelper.GetUserRole(id);

            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ApplicationUser user)
        {
            ModelState.Remove("Password");
            ModelState.Remove("PasswordConfirmed");
            ModelState.Remove("Order");
            if (user.Email == null) ModelState.AddModelError("Email", "Email is required.");
            if (!_fnHelper.IsEmailValid(user.Email)) ModelState.AddModelError("Email", "Email is invalid");


            if (ModelState.IsValid)
            {
                var u = await _userManager.FindByIdAsync(user.Id);

                u.FirstName = user.FirstName;
                u.LastName = user.LastName;
                u.Address = user.Address;
                u.City = user.City;
                u.PostalCode = user.PostalCode;
                u.Country = user.Country;

                var userRole = await _userManager.GetRolesAsync(u);

                if (userRole.Count > 0 && (userRole[0] != user.UserRole))
                {
                    
                    await _userManager.RemoveFromRolesAsync(u, new List<string> { userRole[0] });
                    await _userManager.AddToRoleAsync(u, user.UserRole);
                   
                }

                await _userManager.UpdateAsync(u);

               
                return RedirectToAction("Edit",new { id = user.Id, message = "Changes saved."});
                
            }

            ViewBag.SelectCountry = _context.Country;
            ViewBag.UserRoles = _roleManager.Roles;
            return View(user);
        }


        public IActionResult Delete(string? id)
        {
            if (id == null) return RedirectToAction("Index", new { error = "User not found." });


            var user = _context.Users.Where(x => x.Id == id).FirstOrDefault();

            if (user == null) return RedirectToAction("Index", new { error = "User not found." });
            user.UserRole = _fnHelper.GetUserRole(user.Id);

            return View(user);
        }

        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(string? id)
        {
            if (id == null) return RedirectToAction("Index", new { error = "User not found." });
            
            var user = _context.Users.Find(id);

            if (user != null)
            {
                await _userManager.DeleteAsync(user);
            }else
            {
                return RedirectToAction("Index", new { error = "User not found." });
            }

            return RedirectToAction("Index", new { message = $"User {user.UserName} deleted." }); ;

        }

        public IActionResult CreateUser()
        {
            
            ViewBag.UserRoles = _roleManager.Roles;
            ViewBag.SelectCountry = _context.Country;
            return View();
        }

        [HttpPost] 
        public async Task<IActionResult> CreateUser(ApplicationUser user)
        {
            if (user.UserRole == "Pick Role") ModelState.AddModelError("UserRole", "Role not selected.");
            if (user.Country == "Select country") ModelState.AddModelError("Country", "Country not selected.");
            if (user.Email == null) ModelState.AddModelError("Email", "Email is required.");
            if (!_fnHelper.IsEmailValid(user.Email)) ModelState.AddModelError("Email", "Email invalid.");


            ModelState.Remove("Order");
            if (ModelState.IsValid)
            {
                if (user.Password != user.PasswordConfirmed)
                {
                    ModelState.AddModelError("Password", "Passwords do not match");
                    ViewBag.SelectCountry = _context.Country;
                    ViewBag.UserRoles = _roleManager.Roles;
                    return View(user);
                }
                var newUser = new ApplicationUser()
                {
                    UserName = user.Email,
                    Email = user.Email,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    Address = user.Address,
                    City = user.City,
                    PostalCode = user.PostalCode,
                    Country = user.Country,
                    EmailConfirmed = true, 
                    PhoneNumberConfirmed = true,
                };


                var userExists = await _userManager.FindByEmailAsync(newUser.Email);
                if (userExists == null)
                {

                    var result = await _userManager.CreateAsync(newUser, user.Password);

                    if(result.Succeeded)
                    {
                        await _userManager.AddToRoleAsync(newUser, user.UserRole);
                    }
                    else
                    { //probably password error
                        ViewBag.SelectCountry = _context.Country;
                        ViewBag.UserRoles = _roleManager.Roles; 
                        List<string> errorList = new List<string>();
                        foreach (var item in result.Errors)
                        {
                            errorList.Add(item.Description);
                        }
                        ViewBag.Error = errorList;
                        return View(user);
                    }
                    
                    

                    return RedirectToAction("Index", new { message = $"User - {user.Email} Created!" });
                }
                else
                {
                    ViewBag.Error = "Email taken!";
                    ViewBag.SelectCountry = _context.Country;
                    ViewBag.UserRoles = _roleManager.Roles;
                    return View(user);
                }



            }
            ViewBag.SelectCountry = _context.Country;
            ViewBag.UserRoles = _roleManager.Roles;
            return View(user);
        }

    }
}

WebShopProject/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using System.Numerics;
using WebShopProject.Data;
using WebShopProject.Extensions;

namespace WebShopProject.Controllers
{
    public class CartController : Controller
    {
        public const string SessionKeyName = "_cart";
        private readonly ApplicationDbContext _context;


        public CartController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<CartItem> cart = HttpContext.Session.GetObjectFromJson<List<CartItem>>(SessionKeyName);

            if (cart == null)
            {
                cart = new List<CartItem>();
            }
       
            foreach (CartItem item in cart)
            {
                item.Product.ProductImage = _context.ProductImage != null ? _context.ProductImage.Where(x => x.ProductId == item.Product.Id).ToList() : null;
                item.PricePerProduct = item.GetTotalPrice();
            }
            return View(cart);
        }

        [HttpPost]
        public IActionResult AddToCart(int productId)
        {
            List<CartItem> cart = HttpContext.Session.GetObjectFromJson<List<CartItem>>(SessionKeyName);
            
            if(cart == null) cart = new List<CartItem>();

            if(cart.Count > 0)
            {
                if(cart.Any(x => x.Product.Id == productId))
                {
                    cart.FirstOrDefault(x => x.Product.Id == productId).Quantity++;
                }
                else
                {
                    CartItem item = new CartItem()
                    {
                        Product = _context.Product.Where(x => x.Id == productId).FirstOrDefault(),
                        Quantity = 1,
                    };

                    cart.Add(item);
                }
                HttpContext.Session.SetObjectAsJson(SessionKeyName, cart);
            }
            else
            {
                CartItem item = new CartItem()
                {
                    Product = _context.Product.Where(x => x.Id == productId).FirstOrDefault(),
                    Quantity = 1,
                };

                cart.Add(item);
                HttpContext.Session.SetObjectAsJson(SessionKeyName, cart);
            }
            
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult RemoveFromCart(int productId)
        {
            List<CartItem> cart = HttpContext.Session.GetObjectFromJson<List<CartItem>>(SessionKeyName);

            if (cart != null && cart.Count > 0)
            {
                cart.Remove(cart.FirstOrDefault(x => x.Product.Id == productId));
            }
            HttpContext.Session.SetObjectAsJson(SessionKeyName, cart);
            return RedirectToAction("Index");
        }

        public IActionResult ChangeCartItemQuantity(int productId, int quantity)
        {
            List<CartItem> cart = HttpContext.Session.GetObjectFromJson<List<CartItem>>(SessionKeyName);

            if (cart != null)
            {
                if (cart.Any(x => x.Product.Id == productId))
                {
                    if (quantity == 0)
                    {
                        cart.Remove(cart.Find(x => x.Product.Id == productId));
                    }
                    else 
                    { 
                        cart.FirstOrDefault(x => x.Product.Id == productId).Quantity = quantity; 
                    }

                    
                }
            }

            HttpContext.Session.SetObjectAsJson(SessionKeyName, cart);
            return RedirectToAction("Index");
        }
    }
}

WebShopProject/Views/Shared/_AdminMenuPartial.cshtml
@using Microsoft.AspNetCore.Identity;
@using WebShopProject.Data;
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@if(User != null)
{
    if(SignInManager.IsSignedIn(User) && await UserManager.IsInRoleAsync(UserManager.GetUserAsync(User).Result,"admin"))
    {
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Admin</a>
            <div class="dropdown-menu" >
                <a class="dropdown-item" asp-controller="AdminCategory" asp-action="Index">Categories</a>
                <a class="dropdown-item" asp-controller="AdminProduct" asp-action="Index">Products</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" asp-controller="AdminOrder" asp-action="Index">Orders</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" asp-controller="AdminUser" asp-action="Index">Users</a>
            </div>
        </li>
    }
}

WebShopProject/Views/Shared/_Layout.cshtml
@using WebShopProject.Extensions
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebShopProject.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebShop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between position-relative">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Products</a>
                        </li>
                       @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@

                        <partial name="_AdminMenuPartial"/>
                        @{
                         var cart = this.Context.Session.GetObjectFromJson<List<CartItem>>("_cart");
                         if(cart != null && cart.Count > 0)
                         {
                            <li class="nav-item position-absolute end-0">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">
                                    Cart(@cart.Count)</a>
                            </li>
                         }
                         else
                         {
                                <li class="nav-item position-absolute end-0">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">
                                        Cart
                                    </a>
                                </li>
                            }
                        }
                    </ul>
                  
                </div>

                <partial name="_LoginPartial" />

            </div>
        </nav>
    </header>
<div class="container-sm">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
</div>

@*    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebShopProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
  
</body>

</html>

WebShopProject/Views/Shared/_OrderItemPartial.cshtml
@model List<WebShopProject.Models.OrderItem>


<table class="table">
    <thead>
        <tr>
            <th>
                Product
            </th>
            <th>
                Quantity
            </th>
            <th>
                Price
            </th>
            <th>
                Total
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @((item.Price * item.Quantity).ToString("0.00")) €
                </td>

            </tr>
        }
    </tbody>
</table>

WebShopProject/Views/Shared/_ProductsPartial.cshtml
@model IEnumerable<WebShopProject.Models.Product>


<div class="row mt-3">
@foreach (var item in Model)
{
    <div class="col-sm-3 mb-5 justify-content-center d-flex">
        <div class="card" style="width: 18rem">
            <div class="container text-center">
                <a  asp-action="ProductDetails" asp-controller="Home" asp-route-id="@item.Id">
                @if (item.ProductImage == null)
                {
                    <img src="~/images/default.png"  class="img-fluid" />
                }
                else
                {
                            <img src="@(item.ProductImage.FirstOrDefault(x => x.IsMainImage == true) != null ? item.ProductImage.FirstOrDefault(x => x.IsMainImage == true).FileName : item.ProductImage.FirstOrDefault().FileName )"
                                 class="img-fluid img-thumbnail mt-3" style="height:15rem" />
                }
                </a>
            </div>
            <div class="card-body">
                <div class="card-title fw-bold">@item.Name</div>
                <p class="card-text"> @item.Description</p>
                <table class="table  table-hover">
                    <thead>
                        <tr>
                            <th>Price</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>@item.Price €</td>
                            <td class="position-relative">

                                <form method="post" class="position-absolute end-0 top-50 translate-middle-y" asp-controller="Cart" asp-action="AddToCart">
                                    <input type="hidden" name="productId" value="@item.Id">
                                    <input type="submit" class="btn btn-success btn-sm" value="Add to cart">
                                </form>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}
</div>