WebShopProject/Controllers/Admin/AdminOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebShopProject.Data;
using WebShopProject.Models;

namespace WebShopProject.Controllers.Admin
{
    [Authorize(Roles = "Admin")]
    public class AdminOrderController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly FnHelper _fnHelper;
        public AdminOrderController(ApplicationDbContext context)
        {
            _context = context;
            _fnHelper = new FnHelper(context);
        }

        // GET: AdminOrder
        public async Task<IActionResult> Index()
        {
              return _context.Order != null ? 
                          View(await _context.Order.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Order'  is null.");
        }

        // GET: AdminOrder/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }

            var order = await _context.Order
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }
            order.OrderItems = _fnHelper.GetOrderItems(id);
            return View(order);
        }

        // GET: AdminOrder/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AdminOrder/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserId,Message,DateCreated,Total,BillingFirstName,BillingLastName,BillingEmail,BillingPhoneNumber,BillingAddress,BillingCity,BillingPostalCode,BillingCountry,ShippingFirstName,ShippingLastName,ShippingEmail,ShippingPhoneNumber,ShippingAddress,ShippingCity,ShippingPostalCode,ShippingCountry")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(order);
        }

        // GET: AdminOrder/Edit/5
        public async Task<IActionResult> Edit(int? id, string? message)
        {
            if(message != null) ViewBag.Message = message;

            if (id == null || _context.Order == null)
            {
                return NotFound();
            }

            var order = await _context.Order.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            
            order.OrderItems = _fnHelper.GetOrderItems(id);

            ViewBag.SelectCountry = _context.Country.ToList();
            return View(order);
        }

        // POST: AdminOrder/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId,Message,DateCreated,Total,BillingFirstName,BillingLastName,BillingEmail,BillingPhoneNumber,BillingAddress,BillingCity,BillingPostalCode,BillingCountry,ShippingFirstName,ShippingLastName,ShippingEmail,ShippingPhoneNumber,ShippingAddress,ShippingCity,ShippingPostalCode,ShippingCountry")] Order order)
        {
            if (id != order.Id)
            {
                return NotFound();
            }
            ModelState.Remove("OrderItems"); //not editing items here
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Edit",new {message = "Changes saved!"});
            }
            return View(order);
        }

        // GET: AdminOrder/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }

            var order = await _context.Order
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: AdminOrder/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Order == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Order'  is null.");
            }
            var order = await _context.Order.FindAsync(id);
            if (order != null)
            {

                foreach (var item in _context.OrderItem.Where(x => x.OrderId == id))
                {
                    _context.Product.Find(item.ProductId).Quantity += item.Quantity;
                    _context.OrderItem.Remove(item);
                }

                _context.Order.Remove(order);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
          return (_context.Order?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebShopProject/Controllers/Admin/AdminOrderItemController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebShopProject.Data;
using WebShopProject.Models;

namespace WebShopProject.Controllers.Admin
{
    [Authorize(Roles = "Admin")]
    public class AdminOrderItemController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly FnHelper _fnHelper;
        public AdminOrderItemController(ApplicationDbContext context)
        {
            _context= context;
            _fnHelper = new FnHelper(context);
        }


        public IActionResult Index(int? orderId)
        {
            if (orderId == null) return RedirectToAction("Index", "AdminOrder");



            var orderItems = _fnHelper.GetOrderItems(orderId); 
            
            return View(orderItems == null ? new List<OrderItem>() : orderItems);
        }


        public IActionResult Edit(int? id)
        {
            var ordItem = _context.OrderItem.Find(id);
            ordItem.ProductName = _context.Product.Where(x => x.Id == ordItem.ProductId).FirstOrDefault().Name;
            return View(ordItem);
        }

        [HttpPost]
        public IActionResult Edit(OrderItem orderItem)
        {
            if (orderItem.Price <= 0) ModelState.AddModelError("Price", "Price must be greater than 0");
            if(orderItem.Quantity <= 0) ModelState.AddModelError("Quantity", "Quantity must be greater than 0");

            if (ModelState.IsValid)
            {
                var product = _context.Product.Where(x => x.Id == orderItem.ProductId).FirstOrDefault();
                var oldItem = _context.OrderItem.Where(x => x.Id == orderItem.Id).FirstOrDefault();
                var diffQuantity = orderItem.Quantity - oldItem.Quantity;
                var diffPrice = orderItem.Price - oldItem.Price;
                


                if (diffQuantity == 0 && diffPrice == 0) return RedirectToAction("Edit", new { id = orderItem.Id });

                if (diffQuantity < 0)
                {
                    product.Quantity += Math.Abs(diffQuantity);
                }
                else
                {
                    if (product.Quantity > diffQuantity)
                    {
                        product.Quantity -= Math.Abs(diffQuantity);
                    }
                    else
                    {
                        ModelState.AddModelError("Quantity", $"Only {product.Quantity} items are availiable for sale.");
                        //redirect with error product amount not availiable or set to max availiable amount
                    }
                }

                if(diffPrice != 0 || diffQuantity != 0)
                {
                    _context.Order.Find(orderItem.OrderId).Total += (orderItem.Price * orderItem.Quantity) - (oldItem.Price * oldItem.Quantity);
                }
                oldItem.Quantity = orderItem.Quantity; 
                oldItem.Price = orderItem.Price;

                _context.SaveChanges();

                
            }
            
            return View(orderItem);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null) return RedirectToAction("Index");
            
            var orderItem = _context.OrderItem.Find(id);
            orderItem.ProductName = _context.Product.Find(orderItem.ProductId).Name;
            return View(orderItem);
        }
        [HttpPost]
        [ActionName("Delete")]
        public IActionResult DeleteConfirmed(int? id)
        {
            if(id == null) return RedirectToAction("Index", "AdminOrder");

            var orderItem = _context.OrderItem.Find(id);
            var orderId = orderItem.OrderId;
            
            _context.Product.Find(orderItem.ProductId).Quantity += orderItem.Quantity;
            _context.Order.Find(orderItem.OrderId).Total -= (orderItem.Price * orderItem.Quantity);
            _context.OrderItem.Remove(orderItem);
            _context.SaveChanges();

            return RedirectToAction("Edit", "AdminOrder",new { id = orderId });

        }
    }
}

WebShopProject/Views/AdminOrder/Create.cshtml
@model WebShopProject.Models.Order

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class ="form-control" asp-items="ViewBag.UserId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Message" class="control-label"></label>
                <input asp-for="Message" class="form-control" />
                <span asp-validation-for="Message" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateCreated" class="control-label"></label>
                <input asp-for="DateCreated" class="form-control" />
                <span asp-validation-for="DateCreated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Total" class="control-label"></label>
                <input asp-for="Total" class="form-control" />
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BillingFirstName" class="control-label"></label>
                <input asp-for="BillingFirstName" class="form-control" />
                <span asp-validation-for="BillingFirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BillingLastName" class="control-label"></label>
                <input asp-for="BillingLastName" class="form-control" />
                <span asp-validation-for="BillingLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BillingEmail" class="control-label"></label>
                <input asp-for="BillingEmail" class="form-control" />
                <span asp-validation-for="BillingEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BillingPhoneNumber" class="control-label"></label>
                <input asp-for="BillingPhoneNumber" class="form-control" />
                <span asp-validation-for="BillingPhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BillingAddress" class="control-label"></label>
                <input asp-for="BillingAddress" class="form-control" />
                <span asp-validation-for="BillingAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BillingCity" class="control-label"></label>
                <input asp-for="BillingCity" class="form-control" />
                <span asp-validation-for="BillingCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BillingPostalCode" class="control-label"></label>
                <input asp-for="BillingPostalCode" class="form-control" />
                <span asp-validation-for="BillingPostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BillingCountry" class="control-label"></label>
                <input asp-for="BillingCountry" class="form-control" />
                <span asp-validation-for="BillingCountry" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShippingFirstName" class="control-label"></label>
                <input asp-for="ShippingFirstName" class="form-control" />
                <span asp-validation-for="ShippingFirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShippingLastName" class="control-label"></label>
                <input asp-for="ShippingLastName" class="form-control" />
                <span asp-validation-for="ShippingLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShippingEmail" class="control-label"></label>
                <input asp-for="ShippingEmail" class="form-control" />
                <span asp-validation-for="ShippingEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShippingPhoneNumber" class="control-label"></label>
                <input asp-for="ShippingPhoneNumber" class="form-control" />
                <span asp-validation-for="ShippingPhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShippingAddress" class="control-label"></label>
                <input asp-for="ShippingAddress" class="form-control" />
                <span asp-validation-for="ShippingAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShippingCity" class="control-label"></label>
                <input asp-for="ShippingCity" class="form-control" />
                <span asp-validation-for="ShippingCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShippingPostalCode" class="control-label"></label>
                <input asp-for="ShippingPostalCode" class="form-control" />
                <span asp-validation-for="ShippingPostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShippingCountry" class="control-label"></label>
                <input asp-for="ShippingCountry" class="form-control" />
                <span asp-validation-for="ShippingCountry" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebShopProject/Views/AdminOrder/Delete.cshtml
@model WebShopProject.Models.Order

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dt>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Total)
        </dd>
    
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> 
        <a class="btn btn-dark" asp-action="Index">Back to List</a>
    </form>
</div>

WebShopProject/Views/AdminOrder/Details.cshtml
@model WebShopProject.Models.Order

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div class="row">
    <h4>Order</h4>
    <hr />
    <div class="row h6">
        Date created: @Html.DisplayFor(model => model.DateCreated)
    </div>
    <div class="row">
         <table class="table">
            <thead>
                <tr>
                    <th scope="col">@Html.DisplayNameFor(model => model.BillingFirstName)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.BillingFirstName)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.BillingEmail)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.BillingPhoneNumber)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.BillingAddress)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.BillingCity)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.BillingPostalCode)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.BillingCountry)</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>@Html.DisplayFor(model => model.BillingFirstName)</td>
                    <td>@Html.DisplayFor(model => model.BillingLastName)</td>
                    <td>@Html.DisplayFor(model => model.BillingEmail)</td>
                    <td>@Html.DisplayFor(model => model.BillingPhoneNumber)</td>
                    <td>@Html.DisplayFor(model => model.BillingAddress)</td>
                    <td>@Html.DisplayFor(model => model.BillingCity)</td>
                    <td>@Html.DisplayFor(model => model.BillingPostalCode)</td>
                    <td>@Html.DisplayFor(model => model.BillingCountry)</td>
                </tr>
            </tbody>
        </table>
        <hr />

         <table class="table">
            <thead>
                <tr>
                    <th scope="col">@Html.DisplayNameFor(model => model.ShippingFirstName)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.ShippingFirstName)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.ShippingEmail)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.ShippingPhoneNumber)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.ShippingAddress)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.ShippingCity)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.ShippingPostalCode)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.ShippingCountry)</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>@Html.DisplayFor(model => model.ShippingFirstName)</td>
                    <td>@Html.DisplayFor(model => model.ShippingLastName)</td>
                    <td>@Html.DisplayFor(model => model.ShippingEmail)</td>
                    <td>@Html.DisplayFor(model => model.ShippingPhoneNumber)</td>
                    <td>@Html.DisplayFor(model => model.ShippingAddress)</td>
                    <td>@Html.DisplayFor(model => model.ShippingCity)</td>
                    <td>@Html.DisplayFor(model => model.ShippingPostalCode)</td>
                    <td>@Html.DisplayFor(model => model.ShippingCountry)</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="h5">
        Total: @Html.DisplayFor(model => model.Total) €
    </div>
    <div class="h5">
        Message: @Html.DisplayFor(model => model.Message)
    </div>
    <partial name="_OrderItemPartial" model="@Model.OrderItems" />
</div>
<div>
    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> 
    <a class="btn btn-dark" asp-action="Index">Back to List</a>
</div>

WebShopProject/Views/AdminOrder/Edit.cshtml
@model WebShopProject.Models.Order

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Order no.@Model.Id</h4>
<h5>Created on @Model.DateCreated.ToString("dd-MM-yyyy")</h5>
<hr />
@if(ViewBag.Message != null)
{
    <div class="alert alert-success">
        @ViewBag.Message
    </div>
}
<form asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="UserId" />
    <input type="hidden" asp-for="DateCreated" />
    <input type="hidden" asp-for="Total" />
    <div class="row">
        <table class="table">
            <thead>
                <tr>
                    <th><label asp-for="BillingFirstName" class="control-label"></label></th>
                    <th><label asp-for="BillingLastName" class="control-label"></label></th>
                    <th><label asp-for="BillingEmail" class="control-label"></label></th>
                    <th><label asp-for="BillingPhoneNumber" class="control-label"></label></th>
                    <th><label asp-for="BillingAddress" class="control-label"></label></th>
                    <th><label asp-for="BillingCity" class="control-label"></label></th>
                    <th><label asp-for="BillingPostalCode" class="control-label"></label></th>
                    <th><label asp-for="BillingCountry" class="control-label"></label></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <input asp-for="BillingFirstName" class="form-control" />
                        <span asp-validation-for="BillingFirstName" class="text-danger"></span>
                    </td>
                    <td>
                        <input asp-for="BillingLastName" class="form-control" />
                        <span asp-validation-for="BillingLastName" class="text-danger"></span>
                    </td>
                    <td>
                        <input asp-for="BillingEmail" class="form-control" />
                        <span asp-validation-for="BillingEmail" class="text-danger"></span>
                    </td>
                    <td>
                        <input asp-for="BillingPhoneNumber" class="form-control" />
                        <span asp-validation-for="BillingPhoneNumber" class="text-danger"></span>
                    </td>
                    <td>
                        <input asp-for="BillingAddress" class="form-control" />
                        <span asp-validation-for="BillingAddress" class="text-danger"></span>
                    </td>
                    <td>
                        <input asp-for="BillingCity" class="form-control" />
                        <span asp-validation-for="BillingCity" class="text-danger"></span>
                    </td>
                    <td>
                        <input asp-for="BillingPostalCode" class="form-control" />
                        <span asp-validation-for="BillingPostalCode" class="text-danger"></span>
                    </td>
                    <td>
                        <select asp-for="BillingCountry" class="form-select">
                            <option selected>Select country:</option>
                            @foreach(var item in ViewBag.SelectCountry)
                            {
                                <option value="@item.Name">@item.Name</option>
                            }
                        </select>
                        <span asp-validation-for="BillingCountry" class="text-danger"></span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="row">
        <table class="table">
            <thead>
                <tr>
                    <th><label asp-for="ShippingFirstName" class="control-label"></label></th>
                    <th><label asp-for="ShippingLastName" class="control-label"></label></th>
                    <th><label asp-for="ShippingEmail" class="control-label"></label></th>
                    <th><label asp-for="ShippingPhoneNumber" class="control-label"></label></th>
                    <th><label asp-for="ShippingAddress" class="control-label"></label></th>
                    <th><label asp-for="ShippingCity" class="control-label"></label></th>
                    <th><label asp-for="ShippingPostalCode" class="control-label"></label></th>
                    <th><label asp-for="ShippingCountry" class="control-label"></label></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <input asp-for="ShippingFirstName" class="form-control" />
                        <span asp-validation-for="ShippingFirstName" class="text-danger"></span>
                    </td>
                    <td>
                        <input asp-for="ShippingLastName" class="form-control" />
                        <span asp-validation-for="ShippingLastName" class="text-danger"></span>
                    </td>
                    <td>
                        <input asp-for="ShippingEmail" class="form-control" />
                        <span asp-validation-for="ShippingEmail" class="text-danger"></span>
                    </td>
                    <td>
                        <input asp-for="ShippingPhoneNumber" class="form-control" />
                        <span asp-validation-for="ShippingPhoneNumber" class="text-danger"></span>
                    </td>
                    <td>
                        <input asp-for="ShippingAddress" class="form-control" />
                        <span asp-validation-for="ShippingAddress" class="text-danger"></span>
                    </td>
                    <td>
                        <input asp-for="ShippingCity" class="form-control" />
                        <span asp-validation-for="ShippingCity" class="text-danger"></span>
                    </td>
                    <td>
                        <input asp-for="ShippingPostalCode" class="form-control" />
                        <span asp-validation-for="ShippingPostalCode" class="text-danger"></span>
                    </td>
                    <td>
                        <select asp-for="ShippingCountry" class="form-select">
                            <option selected>Select country:</option>
                            @foreach(var item in ViewBag.SelectCountry)
                            {
                                <option value="@item.Name">@item.Name</option>
                            }
                        </select>
                        <span asp-validation-for="ShippingCountry" class="text-danger"></span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="form-group">
        <label asp-for="Message" class="control-label"></label>
        <textarea asp-for="Message" class="form-control"></textarea>
        <span asp-validation-for="Message" class="text-danger"></span>
    </div>
    <div class="h5 d-inline-flex  mt-2">
        <label asp-for="Total" class="control-label">Total:</label>
        <div class="ms-2">
            @Html.DisplayFor(Model => Model.Total) €
        </div>
        <span asp-validation-for="Total" class="text-danger"></span>
    </div>

    <partial name="_OrderItemPartial" model="@Model.OrderItems"/>

    <div class="form-group mt-3">
        <input type="submit" value="Save" class="btn btn-primary" />
        <a class="btn btn-warning" asp-action="Index" asp-controller="AdminOrderItem" asp-route-orderId="@Model.Id" >Edit order items</a>
        <a class="btn btn-dark" asp-action="Index">Back to Orders</a>
    </div>
</form>

<div>
 
</div>

WebShopProject/Views/AdminOrder/Index.cshtml
@model IEnumerable<WebShopProject.Models.Order>

@{
    ViewData["Title"] = "Index";
}

<h1>Order administration</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DateCreated)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.BillingFirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BillingLastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Total)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr class="align-middle">
            <td>
                @Html.DisplayFor(modelItem => item.DateCreated)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.BillingFirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BillingLastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Total) €
            </td>
            <td>
                <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.Id">Edit</a> 
                <a class="btn btn-warning" asp-action="Details" asp-route-id="@item.Id">Details</a> 
                <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
<div>
    <a class="btn btn-dark" asp-action="Index" asp-controller="Home">Home</a>
</div>